# Site settings
title: "VSON"
author:
  name: Jeff Walker Code Ranger
  email: Jeff@WalkerCodeRanger.com
description:
  "VSON (Very Simple Object Notation) is a lightweight data-interchange format. It is a successor and superset of the popular JSON (JavaScript Object Notation) format. VSON improves on human readability and writablity, date and time support, Unicode handling and data portability."
url: "http://VSON.org"

permalink: /blog/:year/:month/:title
paginate: 5
paginate_path: "/blog/page:num"
encoding: UTF-8

# Build settings
markdown: kramdown
highlights: pygments