ComplexDiagram(
	Choice(0,
		NonTerminal('string'),
		NonTerminal('number'),
		NonTerminal('dateTime'),
		NonTerminal('object'),
		NonTerminal('array'),
		Terminal('true'),
		Terminal('false'),
		Terminal('null')))